### ISSUE TITLE
How to use echarts offline?

### ISSUE THREAD

**Issue by bubifengyun** [hisune/Echarts-PHP#1]
你好，我的网站无法访问外网。在yii2，php下开发。我也看到你的配置里有

``` php
 public static $dist = 'https://cdnjs.cloudflare.com/ajax/libs/echarts/2.2.5';
```

我想把他替换为本地已经下载好的echarts，可有好的办法吗？
或者可以把这个方法写在readme.md里。
谢谢。

**Comment by hisune** [comment]
如果需要以yii2的方式加载前端文件，需要注册asset目录。以下是更简单直接一点的解决办法：

``` php
Hisune\EchartsPHP\Config::$dist = dirname(yii::$app->request->getScriptUrl()) . '/js/echarts';
```

echarts的js文件放在web/js/echarts中即可

**Comment by bubifengyun** [comment]
我觉得放在web/js/echarts这种方式代码构架不好。可能注册asset的方式会好点吧。

**Comment by hisune** [comment]
就yii的规范来说，肯定是注册asset目录的方式更规范，但这个Echarts-PHP不是一个yii插件。

**Comment by bubifengyun** [comment]
只好先应急了。后续成熟了，争取把echarts跟yii2的接口过程给总结一下。
