### ISSUE TITLE
怎么使用getDataURL这个方法去获取生成的图片

### ISSUE THREAD

**Issue by hel2o** [hisune/Echarts-PHP#10]
有一个需求，直接在后台生成echarts的图片，查看echarts文档有一个方法是getDataURL去获取一串base64信息，但你这个Echarts-PHP不知道能不能使用这种方法在后台就直接得到这一串base64字符？

**Comment by hisune** [comment]
后台是无法生成echarts图片的，这个是js的方法，php并不能使用echarts的js方法。你只能在前端使用getDataURL方法，例如：
```js
var echart = chart_<?=$chart->getJsVar()?>,
    image = echart.getDataURL('png');
```

**Comment by hel2o** [comment]
好的，谢谢
