### ISSUE TITLE
Styling a title?

### ISSUE THREAD

**Issue by gflauder** [hisune/Echarts-PHP#11]
Hi there,

I've tried this a few ways, but can't seem to center the title? Any ideas what I'm doing wrong?

` $chart1->title->textStyle = ['align'=>'center'];`

and
`          <div class="row">
            <div class="col-md-4">
                <div>
                    {!! $chart1->render('simple-custom-id') !!}
                </div>
            </div>
            <div class="col-md-8">
                {!! $chart2->render('simple-custom-id2') !!}
            </div>
        </div>`

What might I be missing?
Thanks!

**Comment by hisune** [comment]
This is not echartsphp's problem, maybe you can go to https://github.com/ecomfe/echarts/issues

**Comment by gflauder** [comment]
Thanks, yes, will post the bug over there.
