### ISSUE TITLE
Usage of Config:: with a defined $chart

### ISSUE THREAD

**Issue by gflauder** [hisune/Echarts-PHP#12]
Hi, 
Trying to make the config work, but I'm not really getting it. I know the code below is wrong, but I'm not getting the syntax? 

I have the following for example, curios how Config::  is supposed to be used in a defined chart to make it work?

 ` $chart1 = new ECharts();
$chart1->xAxis->axisLabel =>Config::jsExpr('formatter' => "
        function (v)
        {
            switch (v+''){
                case '10': return 'here;
                case '30': return 'is;
                case '60': return 'a;
                case '90': return 'cool';
                default: return '';
            }
            "
    );`

Thanks!

Gary

**Comment by hisune** [comment]
try this:
```php
$chart1->xAxis->axisLabel = [
    'formatter' => Config::jsExpr("function (v) { switch (v+''){ case '10': return 'here; case '30': return 'is; case '60': return 'a; case '90': return 'cool'; default: return ''; } " )
];
```

**Comment by gflauder** [comment]
Thank you again hisune, 
Perfect, I just wasn't sure about the syntax. Makes perfect sense now and renders script properly. 


I'm having other issues with the echarts itself though as soon as I try changing xaxis. Have posted the bug over at echarts.

https://github.com/ecomfe/echarts/issues/6900

Thanks for your help!
