### ISSUE TITLE
Code not rendering guage properly

### ISSUE THREAD

**Issue by gflauder** [hisune/Echarts-PHP#13]
Hi there,

Sorry to barrage you with quesitons:

Can't seem to customize the guage. 

`        $chart1 = new ECharts();
        $chart1->tooltip->show = true;
        $chart1->tooltip->formatter = "{a} <br/>$ {c} ";
        $chart1->title->text= "Tracking to Goal";
        $chart1->title->textStyle = ['align'=>'center'];
        $chart1->title->subtext ='Last 12 Months 000\'s';
        $chart1->series[] = array(
            'name' => 'Revenue',
            'type' => 'gauge',
            'max' => $chart1data['totalbudget'],
            'data' => $chart1data['totalsales'],
            'show'=> true,
            'lineStyle' => array(
            'color'=> [[0.2, 'lightgreen'],[0.4, 'orange'],[0.8, 'skyblue'],[1, '#ff4500']],
            'width'=> 30,
        ));`

Any idea what I'm doing wrong?

Kind regards

**Comment by hisune** [comment]
What do you mean can't seem to customize the guage? You can use view-source in your browser to check your echart option

**Comment by gflauder** [comment]
Thanks Hisune,
Nothing to do with your package as I'm starting to realize. 

Getting errors like "Cannot read property ""Cannot read property 'coordinateSystem' of undefined"" in the echarts.min.js file

Have posted these over at echarts.

Thanks for looking at this!
