### ISSUE TITLE
 toolbox 不显示问题

### ISSUE THREAD

**Issue by daishiqi** [hisune/Echarts-PHP#14]
$chart->toolbox->show=true;
 但是渲染的页面未显示帮助工具

**Comment by hisune** [comment]
@daishiqi 貌似是你开启了toolbox后，还要设置需要显示的工具内容，例如：`$chart->toolbox->feature->magicType->type = ['line', 'bar'];`

**Comment by daishiqi** [comment]
是的是的，还有个问题。
$chart->toolbox->feature->magicType->type=array('line', 'bar');
设置之后，折线图和柱状图上面就不显示具体数据信息了。

![image](https://user-images.githubusercontent.com/24859249/32765561-f90c9e54-c945-11e7-88f2-96129dd3c2f6.png)

**Comment by hisune** [comment]
@daishiqi 请自行检查生成的options，这个应该是你自己的配置问题，没有其他问题了，我就关闭这个问题了

**Comment by daishiqi** [comment]
还有 series 怎么设置它的位置？


$chart->series = array(
            [
                'name' => '销量',
                'type' => 'line',
                'data' => $value,
            ],
            [
                'name' => '销售金额',
                'type' => 'line',
                'data' => $branch_price,
            ],
            [
                'name' => '成本',
                'type' => 'line',
                'data' => $base_price,
            ],
            [
                'name' => '毛利',
                'type' => 'line',
                'data' => $profit,
            ],
        );


我现在是这么写的

**Comment by hisune** [comment]
@daishiqi 不懂你的意思呀，你其实可以去看echarts的官方options的文档
