### ISSUE TITLE
Invalid filename for windows 

### ISSUE THREAD

**Issue by spmsupun** [hisune/Echarts-PHP#15]
You  can not create file name with greater-than sign( **>**) or less than sign (**<**)
Echarts-PHP/tree/1.0.11/src/Doc/IDE/AngleAxis/AxisLabel/Rich/<user defined style name>.php

**Comment by hisune** [comment]
because of `http://echarts.baidu.com/documents/cn/option.json` have mistake. [fixed](https://github.com/hisune/Echarts-PHP/commit/354899710ef0ed57a42f950d82f0fc05ab9ea21f)
