### ISSUE TITLE
实例化echarts对象的变量名

### ISSUE THREAD

**Issue by easydowork** [hisune/Echarts-PHP#18]
看到源代码是 ECharts 类有一个 setJsVar 方法，但是同个界面有多个 ECharts 实例去渲染的时候 不能自定义js echarts的 init 方法的变量，反而变成了同一个最后自定义的变量了。这个问题导致在 ajax 请求的时候不拿不到自定义的变量去更改图表的数据（getOption()）。看到源码是 Config 类的 静态属性 $jsVar 我只能在每次 ECharts 类 渲染数据前 (render()) 去 使用如下代码：
```php
Config::$jsVar = $echarts->getJsVar();
```
这样每次个 render() 前面都会多这个一句代码，不知道这个算不算是一个小问题哦。

**Comment by hisune** [comment]
实际上，你不用去关心`Config::$jsVar`的变量值，而只需要用 `$echarts->getJsVar()`去获取当前图表的变量名，例如：
```
$chart = new ECharts();
// ...
$var = $chart->getJsVar(true);

$chart2 = new ECharts();
// ...
$var2 = $chart2->getJsVar(true);
```

**Comment by hisune** [comment]
如果还有问题可再打开此问题
