### ISSUE TITLE
add chart/image on FPDF

### ISSUE THREAD

**Issue by mendozada** [hisune/Echarts-PHP#19]
Hello, if it is possible to generate the graph to put it inside a pdf generated with Fpdf inside the script in php?

how to make it generate a base64 image from php

Thanks and regards

**Comment by hisune** [comment]
No, it is not possible
you can use echarts api like
```
image = echart.getDataURL('png');
```
or use [casperjs](http://casperjs.org/) to save screenshot of your chart page

**Comment by mendozada** [comment]
Ok, Thanks
