### ISSUE TITLE
我写了一个在yii2中使用该插件的流程，可否加入你的readme.md?

### ISSUE THREAD

**Issue by bubifengyun** [hisune/Echarts-PHP#2]
参考[这里](https://github.com/hisune/Echarts-PHP)。

对于联网的网站，可以采用上述网址里的做法。下面叙述对无法联网的或者想把echarts下载后放在自己网站离线使用的做法。

百度的echarts为JavaScript/CSS包，采用Bower管理。可以采用如下方式在YII2中使用。
假设你的网站目录为_./basic_。
#1. 下载echarts。

下载[百度](http://echarts.baidu.com/)的echarts-2.2.7.zip压缩包，解压缩后放在
_./basic/vendor/bower/echarts-2.2.7/_下。
#2. 重命名echarts(非必须)。

查看目录_./basic/vendor/bower/echarts-2.2.7/_下面应该有_build,src,doc_等文件夹以及_bower.json,LICENSE.txt_等文件。为方便使用，把文件夹_echarts-2.2.7_改为_echarts_。
#3. 修改_composer.json_文件。

``` bash
vi ./basic/composer.json
```

找到**_require**_这一项，应该有类似如下的内容。

```
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "phpoffice/phpexcel": "^1.8"
    },
```

在最后一行加入**_"bower-asset/echarts": ">=2.2.1"**_，
变成如下形式。

```
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "phpoffice/phpexcel": "^1.8",
        "bower-asset/echarts": ">=2.2.7"
    },
```
#4. 创建asset bundle类。

在目录_./basic/assets/_创建EchartsAsset.php文件。内容如下。

``` php

/**
 * Write Asset for Echarts.
 */

namespace app\assets;

use yii\web\AssetBundle;

class EchartsAsset extends AssetBundle
{
    public $sourcePath = '@bower/echarts/build/dist';
    public $js = [
        'echarts.js',
    ];
}
```

内容参照AssetBundle的教程做的。通过查阅echarts的教程，发现一般他们调用的都是_./echarts/build/dist/_的内容，所以文中设置_$sourcePath_指向该文件夹。
其中_@bower_，YII2会自动找到_./basic/vendor/bower/_文件夹的。
_$js_是查找_./echarts/build/dist/_下的_js_文件，列出来的。
这样完成了AssetBundle的配置。
#5. 安装Echarts-PHP插件。

在目录_./basic/_下输入命令

``` bash
composer require "hisune/echarts-php"
```

或者类似的命令或者直接在[github](https://github.com/hisune/Echarts-PHP)下载，
解压缩放在目录_./basic/vendor/_下。
#6. 输出echarts图像。

下面举个简单的例子。
打开_site/index.php_文件。

``` bash
vi ./basic/views/site/index.php
```

加入如下内容

``` php

<?php 
use app\assets\EchartsAsset;
use Hisune\EchartsPHP\ECharts;

$asset=EchartsAsset::register($this);
$chart = new ECharts($asset->baseUrl);
$chart->tooltip->show = true;
$chart->legend->data = array('销量');
$chart->xAxis = array(
    array(
        'type' => 'category',
        'data' => array("衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子")
    )
);
$chart->yAxis = array(
    array('type' => 'value')
);
$chart->series = array(
    array(
        'name' => '销量',
        'type' => 'bar',
        'data' => array(5, 20, 40, 10, 10, 20)
    )
);
echo $chart->render('simple-custom-id');
```

解说：
第一第二行代码是加入我们需要的类EchartsAsset跟EchartsPHP。

第三行空，第四行第五行注册EchartsAsset类，并把注册后的_baseUrl_传递给EchartsPHP类，供查找_JavaScript/CSS_文件的位置。

第六行及以后赋值，这个可以参考百度的Echarts实例跟EchartsPHP的配置。自己找规律。

最后一行，输出图像。

**Comment by hisune** [comment]
不好意思，最近都比较忙，有空我会整理一下的，感谢提供方法哈。
