### ISSUE TITLE
Working with Echarts-PHP on an API response "_options" Added

### ISSUE THREAD

**Issue by TnCoders** [hisune/Echarts-PHP#26]
HI,

I'm using Echart 4 with Angular for the front End, and i'm sending  Api Call to A Php Controller That return a json response.
my problem is when i use : 
`$chart = new ECharts();`
 `$chart->legend->show =  false;`

when i send back the object $chart i get this:
`
"tooltip": {
                "_options": {
                    "show": true,
                    "trigger": "item",
                }
            },`

the ` "_options": `surround my data and i dont need that surround how can i get this response without ` "_options": `so my result will be:
`"tooltip": {
  "show": true,
"trigger": "item",
},`

I have this for all Series also, Can you please show me how

**Comment by hisune** [comment]
Use `json_encode($chart->getOption())` instead of `json_encode($chart)`

**Comment by TnCoders** [comment]
Hi Thank you for your quick reply it solved my problem but it create another issue:
I use specefic javascript function for tooltip formater  like this : 

 `$chart->tooltip->formatter = '
            function(params, ticket, callback) {
            if(params.name != "")
                {
                if(params.name == \"2016\")
                    return \"Total Sample: \" + params.value + \"<br/> Total 2016 Sample : 11\";
                    else if(params.name==\"2017\")
                    return \"Total Sample: \" + params.value + \"<br/> Total 2017 Sample : 10\";
                    else 
                    return \"Total Sample: \" + params.value + \"<br/> Total 2018 Sample : 12\";
                 }
              else
                 return "";'
            ;`

It become:
         `   "formatter": "{%bea43dc2fdafc34279d7e1a4975fe45c%}" `


How can i avoid this ? Thank you for your help

**Comment by TnCoders** [comment]
I used this also:

$chart->tooltip->formatter = Config::jsExpr('function(params, ticket, callback) {
        if(params.name != "")
            {
            if(params.name == \"2016\")
                return \"Total Sample: \" + params.value + \"<br/> Total 2016 Sample : 11\";
                else if(params.name==\"2017\")
                return \"Total Sample: \" + params.value + \"<br/> Total 2017 Sample : 10\";
                else 
                return \"Total Sample: \" + params.value + \"<br/> Total 2018 Sample : 12\";
            }
         else
             return "";')
        ;

Same issues The response formater is coded in a strange string:
            "formatter": "{%aaf03841edf25b7be9269fe3e8ccf56d%}"
EDIT: I think it's the Json Encoded Value of formater params so it's not an issue but it work when rendred in Page ?

**Comment by hisune** [comment]
Use `echo $chart->getOption(null, true);` instead of `echo json_encode($chart->getOption());`

**Comment by TnCoders** [comment]
> Use `echo $chart->getOption(null, true);` instead of `echo json_encode($chart->getOption());`

Hisune thank's for the reply, i just found that the response is encoded with : 
_jsMethod to encode it to md5, but if i use tit like that can it be  executed by the browser as normal js ?

**Comment by hisune** [comment]
Yes, it can be executed if your syntax is correct.

**Comment by TnCoders** [comment]
> Yes, it can be executed if your syntax is correct.

Just tested it not working : 

![capture d ecran 2019-02-14 a 10 47 02](https://user-images.githubusercontent.com/24681177/52778300-fbfc3f80-3045-11e9-9b83-a07c5c4cfdd3.png)

**Comment by hisune** [comment]
> Use `echo $chart->getOption(null, true);` instead of `echo json_encode($chart->getOption());`

try this.

**Comment by TnCoders** [comment]
Hi I used what you Said : (null,true) but now i have backslash all over the json object is there another paramas  to remove backslash on json_encode() function?

**Comment by TnCoders** [comment]
Finaly I Tried it but still have an issue with it : 
i only need to return    
 tooltip: this.tooltip

without double quotes if i use:

$chart->tooltip = Config::jsExpr('this.tooltip');

it suround the this.tooltip with " and it broke Echarts how to avoid having the double quote added please ?
