### ISSUE TITLE
JsExpr Without Double Quotes

### ISSUE THREAD

**Issue by TnCoders** [hisune/Echarts-PHP#27]
#26 it's about the same issue that was closed:
Finaly I Tried it but still have an issue with it :
i only need to return
tooltip: this.tooltip

without double quotes if i use:

$chart->tooltip = Config::jsExpr('this.tooltip');

it suround the this.tooltip with " and it broke Echarts how to avoid having the double quote added please ?

**Comment by hisune** [comment]
According to my test, there is no such problem.
```php
$chart = new ECharts();
$chart->tooltip = \Hisune\EchartsPHP\Config::jsExpr('this.tooltip');
echo $chart->getOption(null, true);
```
```json
{"tooltip":this.tooltip}
```
