### ISSUE TITLE
ECharts class not found

### ISSUE THREAD

**Issue by tenq** [hisune/Echarts-PHP#28]
Hi, I'm using composer to install package.

1. Install via composer
2. include vendor/autoload file
3. based on user choice, I have two files as includes in index.php: graph_complete.php and text_complete.php. When user use first option, in index.php I use require('graph_complete.php') and inside then, I try below, not working too:
```
require_once __DIR__ . '/../../vendor/autoload.php';
use Hisune\EchartsPHP\ECharts;
$chart = new ECharts();
```
another try below, but not working too;
```

require_once (__DIR__ . '/../../vendor/hisune/echarts-php/src/Config.php');
require_once (__DIR__ . '/../../vendor/hisune/echarts-php/src/ECharts.php');

$chart = new ECharts();
```

In all cases, I receive "_<b>Fatal error</b>:  Class 'ECharts' not found_" messages, but files exists in _vendor/hisune_ folder and correct config autoload.

my folder structure is:
- **app**
--- **admin**
------ **modules**
-------- posts
-------- **votes**
------------ index.php
------------ graph_complete.php
------------ text_complete.php
-------- users
-------- widgets
------ vendor

What I'm doing wrong?

**Comment by hisune** [comment]
It seems that some files affect autoload, this problem is not caused by Echarts, plz check your include files.

**Comment by tenq** [comment]
Thanks, I will check.
