### ISSUE TITLE
Not enough examples

### ISSUE THREAD

**Issue by MarcinanProfesjonalista** [hisune/Echarts-PHP#33]
Can You prepare examples how to use Your library with examples from Apache ECharts?

```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
```
How to change it to be usefull with Echarts-PHP

**Comment by MarcinanProfesjonalista** [comment]
More examples please!

**Comment by hisune** [comment]
Echarts-PHP is just an options generator, so more examples can refer to the official options document of Echats

**Comment by MarcinanProfesjonalista** [comment]
Ok. If i find example what i want i will give You know.
