### ISSUE TITLE
cdn 挂了

### ISSUE THREAD

**Issue by chenjiabin** [hisune/Echarts-PHP#34]
https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js

**Comment by hisune** [comment]
jsdelivr被墙了，可以通过设置dist修改你的cdn：
```php
Hisune\EchartsPHP\Config::$dist = 'your dist url'; // default value: //cdn.jsdelivr.net/npm/echarts@5/dist
```

Related issue: https://github.com/apache/echarts/issues/17042
