### ISSUE TITLE
PHP 8.1 Deprecation

### ISSUE THREAD

**Issue by Stefaminator** [hisune/Echarts-PHP#36]
Hey guys, is this project still alive? There is at least one php8.1 deprecation notice.

E_DEPRECATED: Return type of Hisune\EchartsPHP\Property::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

It is present in latest version 1.1.2 from packagist. Maybe it is already fixed in dev-master and you may create a new tag.

**Comment by hisune** [comment]
Will be fixed in the next version, thx ^_^
