### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ndabAP** [hisune/Echarts-PHP#4]
I included require.js but now I get a lot of other errors:

![bildschirmfoto vom 2016-09-11 15-07-07](https://cloud.githubusercontent.com/assets/8510570/18417442/6e52de24-7831-11e6-838b-a3827f17605c.png)

**Comment by hisune** [comment]
It seems like echarts conflict with requirejs. I will check it.

**Comment by hisune** [comment]
You do not need to include require.js
Can you show me your code?
Or try last release https://github.com/hisune/Echarts-PHP/releases/tag/1.0.6
