### ISSUE TITLE
如何实现动态图呢

### ISSUE THREAD

**Issue by caizhenxing** [hisune/Echarts-PHP#5]
请问，安装这个lib后，如何实现动态图呢？

**Comment by hisune** [comment]
动态图也需要一个初始化的options配置，在初始化options配置之后，在前端加一个setInterval定时器定时请求你的后端接口，返回json数据`myChart.addData`插入到echarts图表中。这个是纯前端+后端API的东西，与Echarts-PHP无关。

**Comment by hisune** [comment]
此问题如果没有其他疑问我就关闭了。

**Comment by hisune** [comment]
@caizhenxing 新版本的echarts取消了addData方法，而是直接用setOption方法。可以参考：https://github.com/hisune/Echarts-PHP/blob/master/demo/dynamic.php
