### ISSUE TITLE
在 composer 上发现这个轮子，超级棒。

### ISSUE THREAD

**Issue by tlerbao** [hisune/Echarts-PHP#6]
** 建议一 **

希望有更详细的使用文档和示例，以便我等菜鸡能更好的使用这个超级棒的轮子。

** 建议二 **

PHPStorm 提示 Field Accessed via magic method ，如若能改进甚好（强迫症非必要考虑建议）

**Comment by hisune** [comment]
感谢支持和建议，你的这些建议我都会慎重考虑

**Comment by hisune** [comment]
@tlerbao 
master分支中已经加了IDE的property自动提示的PHPDoc，但有有一些小瑕疵未解决，解决后会将IDE自动提示这个新特性在下一个版本发布。

**Comment by hisune** [comment]
@tlerbao 
新版本已发布，增加了property的自动提示。

**Comment by hisune** [comment]
对于文档的问题，我对文档补充了一些函数说明。问题关闭，有其他疑问欢迎提交issue
