### ISSUE TITLE
生成的图表，比如柱状图，如何能用PHP保存下来呢？谢谢！

### ISSUE THREAD

**Issue by zyuz** [hisune/Echarts-PHP#8]
echarts3中只有toolbox.feature.saveAsImage，那是要等图片显示出来后，再手动一个一个另存为图片的。

能否使用代码方式生成图片，我生成的统计图有好多。谢谢！

**Comment by hisune** [comment]
Echarts-PHP无法获取js生成的具体显示内容或图片，如果你想实现完全自动化的图片下载，可以结合echarts js的getDataURL()方法来实现。例如：`chart.getDataURL('png')`
