### ISSUE TITLE
ｐｈｐ　ｅｃｈａｒｔｓ　多参数问题

### ISSUE THREAD

**Issue by daishiqi** [hisune/Echarts-PHP#9]
composer 安装echarts。
 $chart = new ECharts();
        $chart->tooltip->show = true;
        $chart->legend->data[] =['销量'，‘金额’];// 想添加多个参数，不知道这个地方怎么写，写数组还是什么？ 方便给个案例吗？
        $chart->xAxis[] = array(
            'type' => 'category',
            'data' => $name
    );
        $chart->yAxis[] = array(
            'type' => 'value'
        );
        $chart->series[] = array(//这块的数据是根据legend参数个数填写吗？
            [
                'name' => '销量',
                'type' => 'line',
                'data' => $value,
            ],
            [
                'name' => '金额',
                'type' => 'line',
                'data' => $money,
            ],
        );

根据我上面错误的代码能明白我想要的效果吗？　就是不知道ｌｅｇｅｎｄ　和series多个参数时要怎么写．．．

**Comment by hisune** [comment]
1. 多个data应该是这样：
```php
$chart->legend->data = ['销量'，'金额'];
```
2. series的个数是和data对应的

**Comment by daishiqi** [comment]
1.$chart->legend->data =['销量'，‘金额’];


2.$chart->series = array(
[
'name' => '销量',
'type' => 'line',
'data' => $value,
],
[
'name' => '金额',
'type' => 'line',
'data' => $money,
],
);
这样吗？

**Comment by hisune** [comment]
是的，你可以试试

**Comment by daishiqi** [comment]
嗯呢可以的，非常感谢～～，以后有问题再来问　哈哈哈哈
